<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="homeworkPizzaShop" nsURI="http://www.example.org/homeworkPizzaShop"
    nsPrefix="homeworkPizzaShop">
  <eClassifiers xsi:type="ecore:EClass" name="BrowsingPage" eSuperTypes="#//Webpage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productpage" upperBound="-1"
        eType="#//ProductPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductPage" eSuperTypes="#//Webpage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraWishes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="InPrepartion" value="1"/>
    <eLiterals name="Cancelled" value="2"/>
    <eLiterals name="InDelivery" value="3"/>
    <eLiterals name="ReadyForPickup" value="4"/>
    <eLiterals name="Completed" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShoppingCart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discrount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
        eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cartitem" upperBound="-1"
        eType="#//CartItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cartitem" lowerBound="1"
        upperBound="-1" eType="#//CartItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employeeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Webpage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationPage" eSuperTypes="#//Webpage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LandingPage" eSuperTypes="#//Webpage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="welcomeMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="OnSale"/>
    <eLiterals name="Vegan" value="1"/>
    <eLiterals name="Vegetarian" value="2"/>
    <eLiterals name="Meat" value="3"/>
    <eLiterals name="Snacks" value="4"/>
    <eLiterals name="GlutenFree" value="5"/>
    <eLiterals name="Dessert" value="6" literal="Dessert"/>
    <eLiterals name="Softdrinks" value="7"/>
    <eLiterals name="Milkshake" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" lowerBound="1"
        eType="#//Payment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
        upperBound="-1" eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" lowerBound="1"
        upperBound="-1" eType="#//Employee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openingHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" lowerBound="1"
        upperBound="-1" eType="#//Employee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Webapplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storemanagementsystem"
        lowerBound="1" eType="#//StoreManagementSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webpage" lowerBound="1"
        upperBound="-1" eType="#//Webpage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creditCardInfomration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSucessful" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoreManagementSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1" eType="#//Store"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" lowerBound="1" upperBound="-1"
        eType="#//Order" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
